// This file is auto-generated by mockupPreviewPlugin.ts but edited for manual routing mapping.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  'AdminDashboard': () => import('../components/ui/card').then(m => m), // temporary bundle hooks
  'DriverDashboard': () => import('../components/ui/card').then(m => m)
};
